app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    ports:
      - "8443:8443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_HOST=tm-unifi-network-application_unifi-db_1
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_password
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=unifi
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
    depends_on:
      - unifi-db
```

Push, reinstall, then go to:
```
https://10.150.40.145:8443
